import os
import logging
import google.generativeai as genai
from fastapi import HTTPException
from .utils import clean_markdown_tables

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY")

def generate_with_google(prompt: str) -> str:
    """Generate using Google AI Studio (Generative AI) API with official SDK"""
    if not GOOGLE_API_KEY:
        raise HTTPException(status_code=500, detail="GOOGLE_API_KEY not configured")
    
    try:
        # Configure the API key
        genai.configure(api_key=GOOGLE_API_KEY)
        
        # Use gemini-2.5-flash directly
        model_name = "gemini-2.5-flash"
        logger.info(f"Using model: {model_name}")
        
        model = genai.GenerativeModel(model_name)
        
        generation_config = {
            "temperature": 0.2,  # Lower temperature for more consistent, accurate content
            "top_k": 40,
            "top_p": 0.95,
            "max_output_tokens": 20000,
        }
        
        response = model.generate_content(
            prompt,
            generation_config=generation_config
        )
        
        result = response.text.strip()
        
        # Log finish reason
        if response.candidates and response.candidates[0].finish_reason:
            finish_reason = response.candidates[0].finish_reason
            if finish_reason == "MAX_TOKENS":
                logger.warning(f"Response may be truncated (finish_reason: {finish_reason})")
            else:
                logger.info(f"Response completed (finish_reason: {finish_reason})")
        
        if result:
            # Clean up malformed markdown tables
            result = clean_markdown_tables(result)
            
            result_length = len(result)
            logger.info(f"Successfully generated content using model: {model_name}")
            logger.info(f"Response length: {result_length} characters")
            return result
        else:
            logger.error(f"Empty response from model {model_name}")
            raise HTTPException(
                status_code=500,
                detail=f"No content generated by {model_name}"
            )
    
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Unexpected error: {str(e)}", exc_info=True)
        raise HTTPException(
            status_code=500,
            detail=f"Failed to generate content: {str(e)}"
        )
